
version: 2.1

jobs:
  hello:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Echo Hello World
          command: echo "Hello World"

workflows:
  main:
    jobs:
      - hello
