
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.15.1
    steps:
      - checkout
      - run:
          name: Install Node Dependencies
          command: |
            npm install
      - run:
          name: Build the App
          command: |
            npm run build
      - run:
          name: Verify Build static files exist
          command: |
            ls -al build

workflows:
  main:
    jobs:
      - build
