
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.15.1
    steps:
      - checkout
      - restore_cache:
          key: node-deps-{{ checksum "package.json" }}
      - run:
          name: Install Node Dependencies
          command: |
            npm install
      - run:
          name: Build the App
          command: |
            npm run build
      - run:
          name: Verify Build static files exist
          command: |
            ls -al build
      - save_cache:
          paths:
            - node_modules
          key: node-deps-{{ checksum "package.json" }}

  test:
    docker:
      - image: cimg/node:16.15.1
    steps:
      - checkout
      - restore_cache:
          key: node-deps-{{ checksum "package.json" }}
      - run:
          name: Install Node Dependencies
          command: |
            npm install
      - run:
          name: Test the App
          command: |
            npm run test

  scan:
    docker:
      - image: cimg/node:16.15.1
    steps:
      - checkout
      - restore_cache:
          key: node-deps-{{ checksum "package.json" }}
      - run:
          name: Install Node Dependencies
          command: |
            npm install
      - run:
          name: Scan the App for critical vulnerabilities
          command: |
            npm audit --audit-level=critical

workflows:
  main:
    jobs:
      - build
      - test:
          requires:
            - build
      - scan:
          requires:
            - build
